package com.online_exam.examer.authentication;

import com.online_exam.examer.admin.AdminRepository;
import com.online_exam.examer.exception.ResourceNotFoundException;
import com.online_exam.examer.exception.SendEmailFailedException;
import com.online_exam.examer.user.UserRepository;
import jakarta.mail.MessagingException;
import jakarta.mail.internet.MimeMessage;
import lombok.RequiredArgsConstructor;
import org.springframework.core.env.Environment;
import org.springframework.mail.SimpleMailMessage;
import org.springframework.mail.javamail.JavaMailSender;
import org.springframework.mail.javamail.MimeMessageHelper;
import org.springframework.stereotype.Service;

import java.util.Objects;

@Service
@RequiredArgsConstructor
public class EmailService {

    private final JavaMailSender mailSender;
    private final AdminRepository adminRepository;
    private final UserRepository userRepository;
    private final Environment environment;



    public void sendOtpEmail(String to, String otp) {

        if(!adminRepository.existsByEmail(to)||adminRepository.existsByEmailAndIsDeletedTrue(to))
        {
            throw new ResourceNotFoundException("Email does not exist");
        }

        try {

            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);

            helper.setFrom(Objects.requireNonNull(environment.getProperty("spring.mail.username")));
            helper.setTo(to);
            helper.setSubject("Your OTP Code");

            String htmlContent = "<html>" +
                    "<head>" +
                    "<style>" +
                    "body {" +
                    "  display: flex;" +
                    "  justify-content: center;" +
                    "  align-items: center;" +
                    "  height: 100vh;" +
                    "  width: 100vw;" +
                    "  margin: 0;" +
                    "  background-color: #f00;" +
                    "}" +
                    ".card {" +
                    "  width: 100%;" +
                    "  display: flex;" +
                    "  justify-content: center;" +
                    "}" +
                    ".content {" +
                    "  padding: 20px;" +
                    "  background-color: #eee;" +
                    "  box-shadow: 1px 2px 4px rgba(0, 0, 0, 0.2);" +
                    "  border-radius: 8px;" +
                    "  text-align: center;" +
                    "  font-family: Arial, sans-serif;" +
                    "}" +
                    ".logo {" +
                    "  width: 100px;" +
                    "  margin-bottom: 15px;" +
                    "}" +
                    "h3 {" +
                    "  font-size: 18px;" +
                    "  font-weight: bold;" +
                    "  color: #333;" +
                    "}" +
                    ".otp-label {" +
                    "  display: inline-block;" +
                    "  background-color: #4A3AFF;" +
                    "  color: white;" +
                    "  padding: 10px 20px;" +
                    "  border-radius: 5px;" +
                    "  font-size: 20px;" +
                    "  font-weight: bold;" +
                    "  text-align: center;" +
                    "  margin: 10px;" +
                    "}" +
                    "p {" +
                    "  color: #1C4498;" +
                    "}" +
                    "</style>" +
                    "</head>" +
                    "<body>" +
                    "<div class='card'>" +
                    "<div class='content'>" +
                    "<img src='https://i.imgur.com/qrQufSi.png' alt='Examer Logo' class='logo'/>" + // Logo at the top
                    "<h3>Your OTP Code is:</h3>" +
                    "<div class='otp-label'>" + otp + "</div>" + // Dynamic OTP
                    "<p>Please use this code within 5 minutes.</p>" +
                    "<p>Best regards,<br>Examer Team</p>" +
                    "</div>" +
                    "</div>" +
                    "</body>" +
                    "</html>";





            helper.setText(htmlContent, true);  // The `true` flag indicates HTML content

            mailSender.send(message);
        } catch (MessagingException e) {
            throw new SendEmailFailedException("Failed to send email");
        }
    }

    public void sendAutoGeneratedPassword(String to, String password,String adminUsername) {

        if(!adminRepository.existsByEmail(to))
        {
            throw new ResourceNotFoundException("Email does not exist");
        }

        try {

            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);

            helper.setFrom(Objects.requireNonNull(environment.getProperty("spring.mail.username")));
            helper.setTo(to);
            helper.setCc(new String[]{
                    "onlineexam@ntgclarity.com",
                    "mohamedibrahim@ntgclarity.com"
            });
            helper.setSubject("Your Password");

            String htmlContent = "<html>" +
                    "<head>" +
                    "<style>" +
                    "body {" +
                    "  display: flex;" +
                    "  justify-content: center;" +
                    "  align-items: center;" +
                    "  height: 100vh;" +
                    "  width: 100vw;" +
                    "  margin: 0;" +
                    "  background-color: #f00;" +
                    "}" +
                    ".card {" +
                    "  width: 100%;" +
                    "  display: flex;" +
                    "  justify-content: center;" +
                    "}" +
                    ".content {" +
                    "  padding: 20px;" +
                    "  background-color: #eee;" +
                    "  box-shadow: 1px 2px 4px rgba(0, 0, 0, 0.2);" +
                    "  border-radius: 8px;" +
                    "  text-align: center;" +
                    "  font-family: Arial, sans-serif;" +
                    "}" +
                    ".logo {" +
                    "  width: 100px;" +
                    "  margin-bottom: 15px;" +
                    "}" +
                    "h3 {" +
                    "  font-size: 18px;" +
                    "  font-weight: bold;" +
                    "  color: #333;" +
                    "}" +
                    ".otp-label {" +
                    "  display: inline-block;" +
                    "  background-color: #4A3AFF;" +
                    "  color: white;" +
                    "  padding: 10px 20px;" +
                    "  border-radius: 5px;" +
                    "  font-size: 20px;" +
                    "  font-weight: bold;" +
                    "  text-align: center;" +
                    "  margin: 10px;" +
                    "}" +
                    "p {" +
                    "  color: #1C4498;" +
                    "}" +
                    "</style>" +
                    "</head>" +
                    "<body>" +
                    "<div class='card'>" +
                    "<div class='content'>" +
                    "<img src='https://i.imgur.com/qrQufSi.png' alt='Examer Logo' class='logo'/>" + // Logo at the top
                    "<h3>Your Username is:</h3>" +
                    "<div class='otp-label'>" + adminUsername + "</div><br>"+//admin user name
                    "<h3>Your Password is:</h3>" +
                    "<div class='otp-label'>" + password + "</div>" + //Dynamic password
                    "<p>Please use this username and password to login.</p>" +
                    "<p>Best regards,<br>Examer Team</p>" +
                    "</div>" +
                    "</div>" +
                    "</body>" +
                    "</html>";





            helper.setText(htmlContent, true);  // The `true` flag indicates HTML content

            mailSender.send(message);
        } catch (MessagingException e) {
            e.printStackTrace();
            // You may want to log this exception or handle it further
        }
    }

    public void sendExamLinkToUser(String to, String examLink,String examTitle, int examDuration) {

        if(!userRepository.existsByEmail(to))
        {
            throw new ResourceNotFoundException("Email does not exist");
        }

        try {

            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);

            helper.setFrom(Objects.requireNonNull(environment.getProperty("spring.mail.username")));
            helper.setTo(to);
            helper.setCc(new String[]{
                    "onlineexam@ntgclarity.com",
                    "mohamedibrahim@ntgclarity.com"
            });
            helper.setSubject(examTitle+" Exam Link");

            String htmlContent = "<html>" +
                    "<head>" +
                    "<style>" +
                    "body {" +
                    "  display: flex;" +
                    "  justify-content: center;" +
                    "  align-items: center;" +
                    "  height: 100vh;" +
                    "  width: 100vw;" +
                    "  margin: 0;" +
                    "  background-color: #f00;" +
                    "}" +
                    ".card {" +
                    "  width: 100%;" +
                    "  display: flex;" +
                    "  justify-content: center;" +
                    "}" +
                    ".content {" +
                    "  padding: 20px;" +
                    "  background-color: #eee;" +
                    "  box-shadow: 1px 2px 4px rgba(0, 0, 0, 0.2);" +
                    "  border-radius: 8px;" +
                    "  text-align: center;" +
                    "  font-family: Arial, sans-serif;" +
                    "}" +
                    ".logo {" +
                    "  width: 100px;" +
                    "  margin-bottom: 15px;" +
                    "}" +
                    "h3 {" +
                    "  font-size: 18px;" +
                    "  font-weight: bold;" +
                    "  color: #333;" +
                    "}" +
                    ".otp-label {" +
                    "  display: inline-block;" +
                    "  background-color: #4A3AFF;" +
                    "  color: white;" +
                    "  padding: 10px 20px;" +
                    "  border-radius: 5px;" +
                    "  font-size: 20px;" +
                    "  font-weight: bold;" +
                    "  text-align: center;" +
                    "  margin: 10px;" +
                    "}" +
                    ".link a {" +
                    "  color: white;" +      // White text color for links
                    "  text-decoration: none;" +  // No underline for links
                    "}" +
                    "p {" +
                    "  color: #1C4498;" +
                    "}" +
                    "</style>" +
                    "</head>" +
                    "<body>" +
                    "<div class='card'>" +
                    "<div class='content'>" +
                    "<img src='https://i.imgur.com/qrQufSi.png' alt='Examer Logo' class='logo'/>" +
                    "<h3>To take your exam click the the button below:</h3>" +
                    "<div class='otp-label'>" + "<div class='link'><a href='" + examLink + "'>" + "Take Exam" + "</a></div>" + "</div><br>" +
                    "<p>Note: the exam duration is " + examDuration + "Min"+ "</p>" +
                    "<p>Best regards,<br>Examer Team</p>" +
                    "</div>" +
                    "</div>" +
                    "</body>" +
                    "</html>";







            helper.setText(htmlContent, true);  // The `true` flag indicates HTML content

            mailSender.send(message);
        } catch (MessagingException e) {
            e.printStackTrace();
            // You may want to log this exception or handle it further
        }
    }

    public void sendContactEmail(String from, String subject, String userMessage) {


        try {

            MimeMessage message = mailSender.createMimeMessage();
            MimeMessageHelper helper = new MimeMessageHelper(message, true);

            helper.setTo(Objects.requireNonNull(environment.getProperty("spring.mail.username")));
            // Set the user’s email in the "from" field
            helper.setFrom(from);

            // Set a "Reply-To" address to the user’s email, so replies go directly to the user
            helper.setReplyTo(from);
            helper.setSubject(subject);
            String emailContent = "<p><strong>Sender Email:</strong> " + from + "</p>" +
                    "<p><strong>Message Content:</strong><br>" + userMessage + "</p>" +
                    "<p style='color: #1C4498;'><em>This message was sent from a user to the support team.</em></p>";

            // Set the content as HTML
            helper.setText(emailContent, true);
            mailSender.send(message);
        } catch (MessagingException e) {
            e.printStackTrace();
            // You may want to log this exception or handle it further
        }
    }


}